name: Playwright Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: get new commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '1 hour ago' | wc -l)" >> $GITHUB_ENV
      - name: Install dependencies
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        run: npm ci
      - name: Check token
        run: export token=${{ secrets.SLACK_SECRET }}
      - name: Install Playwright Browsers
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        id: playwrightTest
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        continue-on-error: true
        run: npm run test

      - name: print code
        run: echo "Outcome is ${{steps.hello.playwrightTest}}"

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        with:
          channel-id: "C05271QMGPR"
          payload: |
            {
             "text": "GitHub Action build result testing: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
             "blocks":[
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
                   "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                 }
               }
             ]
            }
